require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NotifyTemplatesController do

  # This should return the minimal set of attributes required to create a valid
  # NotifyTemplate. As you add validations to NotifyTemplate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "template_name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NotifyTemplatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all notify_templates as @notify_templates" do
      notify_template = NotifyTemplate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:notify_templates).should eq([notify_template])
    end
  end

  describe "GET show" do
    it "assigns the requested notify_template as @notify_template" do
      notify_template = NotifyTemplate.create! valid_attributes
      get :show, {:id => notify_template.to_param}, valid_session
      assigns(:notify_template).should eq(notify_template)
    end
  end

  describe "GET new" do
    it "assigns a new notify_template as @notify_template" do
      get :new, {}, valid_session
      assigns(:notify_template).should be_a_new(NotifyTemplate)
    end
  end

  describe "GET edit" do
    it "assigns the requested notify_template as @notify_template" do
      notify_template = NotifyTemplate.create! valid_attributes
      get :edit, {:id => notify_template.to_param}, valid_session
      assigns(:notify_template).should eq(notify_template)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NotifyTemplate" do
        expect {
          post :create, {:notify_template => valid_attributes}, valid_session
        }.to change(NotifyTemplate, :count).by(1)
      end

      it "assigns a newly created notify_template as @notify_template" do
        post :create, {:notify_template => valid_attributes}, valid_session
        assigns(:notify_template).should be_a(NotifyTemplate)
        assigns(:notify_template).should be_persisted
      end

      it "redirects to the created notify_template" do
        post :create, {:notify_template => valid_attributes}, valid_session
        response.should redirect_to(NotifyTemplate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved notify_template as @notify_template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NotifyTemplate.any_instance.stub(:save).and_return(false)
        post :create, {:notify_template => { "template_name" => "invalid value" }}, valid_session
        assigns(:notify_template).should be_a_new(NotifyTemplate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NotifyTemplate.any_instance.stub(:save).and_return(false)
        post :create, {:notify_template => { "template_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested notify_template" do
        notify_template = NotifyTemplate.create! valid_attributes
        # Assuming there are no other notify_templates in the database, this
        # specifies that the NotifyTemplate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NotifyTemplate.any_instance.should_receive(:update_attributes).with({ "template_name" => "MyString" })
        put :update, {:id => notify_template.to_param, :notify_template => { "template_name" => "MyString" }}, valid_session
      end

      it "assigns the requested notify_template as @notify_template" do
        notify_template = NotifyTemplate.create! valid_attributes
        put :update, {:id => notify_template.to_param, :notify_template => valid_attributes}, valid_session
        assigns(:notify_template).should eq(notify_template)
      end

      it "redirects to the notify_template" do
        notify_template = NotifyTemplate.create! valid_attributes
        put :update, {:id => notify_template.to_param, :notify_template => valid_attributes}, valid_session
        response.should redirect_to(notify_template)
      end
    end

    describe "with invalid params" do
      it "assigns the notify_template as @notify_template" do
        notify_template = NotifyTemplate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NotifyTemplate.any_instance.stub(:save).and_return(false)
        put :update, {:id => notify_template.to_param, :notify_template => { "template_name" => "invalid value" }}, valid_session
        assigns(:notify_template).should eq(notify_template)
      end

      it "re-renders the 'edit' template" do
        notify_template = NotifyTemplate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NotifyTemplate.any_instance.stub(:save).and_return(false)
        put :update, {:id => notify_template.to_param, :notify_template => { "template_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested notify_template" do
      notify_template = NotifyTemplate.create! valid_attributes
      expect {
        delete :destroy, {:id => notify_template.to_param}, valid_session
      }.to change(NotifyTemplate, :count).by(-1)
    end

    it "redirects to the notify_templates list" do
      notify_template = NotifyTemplate.create! valid_attributes
      delete :destroy, {:id => notify_template.to_param}, valid_session
      response.should redirect_to(notify_templates_url)
    end
  end

end
