require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TableHeadersController do

  # This should return the minimal set of attributes required to create a valid
  # TableHeader. As you add validations to TableHeader, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "resource_type_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TableHeadersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all table_headers as @table_headers" do
      table_header = TableHeader.create! valid_attributes
      get :index, {}, valid_session
      assigns(:table_headers).should eq([table_header])
    end
  end

  describe "GET show" do
    it "assigns the requested table_header as @table_header" do
      table_header = TableHeader.create! valid_attributes
      get :show, {:id => table_header.to_param}, valid_session
      assigns(:table_header).should eq(table_header)
    end
  end

  describe "GET new" do
    it "assigns a new table_header as @table_header" do
      get :new, {}, valid_session
      assigns(:table_header).should be_a_new(TableHeader)
    end
  end

  describe "GET edit" do
    it "assigns the requested table_header as @table_header" do
      table_header = TableHeader.create! valid_attributes
      get :edit, {:id => table_header.to_param}, valid_session
      assigns(:table_header).should eq(table_header)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TableHeader" do
        expect {
          post :create, {:table_header => valid_attributes}, valid_session
        }.to change(TableHeader, :count).by(1)
      end

      it "assigns a newly created table_header as @table_header" do
        post :create, {:table_header => valid_attributes}, valid_session
        assigns(:table_header).should be_a(TableHeader)
        assigns(:table_header).should be_persisted
      end

      it "redirects to the created table_header" do
        post :create, {:table_header => valid_attributes}, valid_session
        response.should redirect_to(TableHeader.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved table_header as @table_header" do
        # Trigger the behavior that occurs when invalid params are submitted
        TableHeader.any_instance.stub(:save).and_return(false)
        post :create, {:table_header => { "resource_type_id" => "invalid value" }}, valid_session
        assigns(:table_header).should be_a_new(TableHeader)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TableHeader.any_instance.stub(:save).and_return(false)
        post :create, {:table_header => { "resource_type_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested table_header" do
        table_header = TableHeader.create! valid_attributes
        # Assuming there are no other table_headers in the database, this
        # specifies that the TableHeader created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TableHeader.any_instance.should_receive(:update_attributes).with({ "resource_type_id" => "1" })
        put :update, {:id => table_header.to_param, :table_header => { "resource_type_id" => "1" }}, valid_session
      end

      it "assigns the requested table_header as @table_header" do
        table_header = TableHeader.create! valid_attributes
        put :update, {:id => table_header.to_param, :table_header => valid_attributes}, valid_session
        assigns(:table_header).should eq(table_header)
      end

      it "redirects to the table_header" do
        table_header = TableHeader.create! valid_attributes
        put :update, {:id => table_header.to_param, :table_header => valid_attributes}, valid_session
        response.should redirect_to(table_header)
      end
    end

    describe "with invalid params" do
      it "assigns the table_header as @table_header" do
        table_header = TableHeader.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TableHeader.any_instance.stub(:save).and_return(false)
        put :update, {:id => table_header.to_param, :table_header => { "resource_type_id" => "invalid value" }}, valid_session
        assigns(:table_header).should eq(table_header)
      end

      it "re-renders the 'edit' template" do
        table_header = TableHeader.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TableHeader.any_instance.stub(:save).and_return(false)
        put :update, {:id => table_header.to_param, :table_header => { "resource_type_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested table_header" do
      table_header = TableHeader.create! valid_attributes
      expect {
        delete :destroy, {:id => table_header.to_param}, valid_session
      }.to change(TableHeader, :count).by(-1)
    end

    it "redirects to the table_headers list" do
      table_header = TableHeader.create! valid_attributes
      delete :destroy, {:id => table_header.to_param}, valid_session
      response.should redirect_to(table_headers_url)
    end
  end

end
